Fix image_refs to allow values with secrets

diff --git a/.github/workflows/build-push.yml b/.github/workflows/build-push.yml
--- a/.github/workflows/build-push.yml
+++ b/.github/workflows/build-push.yml
@@ -66,7 +66,7 @@ on:
     outputs:
       image_refs:
         description: 'Comma-separated list of pushed Docker image refs'
-        value: ${{ jobs.prepare.outputs.image_refs }}
+        value: ${{ jobs.push-manifest.outputs.image_refs }}
 
   # Run on manual triggers
   workflow_dispatch:
@@ -148,7 +148,7 @@ jobs:
     outputs:
       build_variant: ${{ steps.outputs.outputs.build_variant }}
       python_image_tag: ${{ steps.outputs.outputs.python_image_tag }}
-      image_refs: ${{ steps.outputs.outputs.image_refs }}
+      image_tags: ${{ steps.outputs.outputs.image_tags }}
       matrix: ${{ steps.outputs.outputs.matrix }}
 
     steps:
@@ -336,60 +336,6 @@ jobs:
 
           set_github_env 'IMAGE_TAGS' "${IMAGE_TAGS}" non-optional non-secret verbose
 
-      - name: Set IMAGE_REFS
-        env:
-          DHCR_ENABLED: ${{ env.DHCR_ENABLED }}
-          DHCR_IMAGES_NAME: ${{ env.DHCR_IMAGES_NAME }}
-          GHCR_ENABLED: ${{ env.GHCR_ENABLED }}
-          GHCR_IMAGES_NAME: ${{ env.GHCR_IMAGES_NAME }}
-          CUSTOM_CR_ENABLED: ${{ env.CUSTOM_CR_ENABLED }}
-          CUSTOM_CR_IMAGES_NAME: ${{ env.CUSTOM_CR_IMAGES_NAME }}
-          IMAGE_TAGS: ${{ env.IMAGE_TAGS }}
-        run: |
-          # Set IMAGE_REFS environment variable
-
-          # Load helper scripts
-          . ./.github/workflows/scripts/set_github_env.sh
-
-          # Break down IMAGE_TAGS into a list of image tags
-          IMAGE_TAGS_LIST="$(
-            printf '%s\n' "$IMAGE_TAGS" \
-            | tr ',' '\n'
-          )"
-
-          IMAGE_REFS=''
-
-          # Include image refs for all tags in Docker Hub registry
-          if [ "${DHCR_ENABLED}" = "true" ] && [ -n "${DHCR_IMAGES_NAME}" ]; then
-            while IFS= read -r image_tag; do
-              IMAGE_REFS="${IMAGE_REFS},${DHCR_IMAGES_NAME}:${image_tag}"
-            done <<< "$IMAGE_TAGS_LIST"
-          fi
-
-          # Include image refs for all tags in GitHub registry
-          if [ "${GHCR_ENABLED}" = "true" ] && [ -n "${GHCR_IMAGES_NAME}" ]; then
-            while IFS= read -r image_tag; do
-              IMAGE_REFS="${IMAGE_REFS},${GHCR_IMAGES_NAME}:${image_tag}"
-            done <<< "$IMAGE_TAGS_LIST"
-          fi
-
-          # Include image refs for all tags in custom registry
-          if [ "${CUSTOM_CR_ENABLED}" = "true" ] && [ -n "${CUSTOM_CR_IMAGES_NAME}" ]; then
-            while IFS= read -r image_tag; do
-              IMAGE_REFS="${IMAGE_REFS},${CUSTOM_CR_IMAGES_NAME}:${image_tag}"
-            done <<< "$IMAGE_TAGS_LIST"
-          fi
-
-          # Remove leading comma
-          IMAGE_REFS=${IMAGE_REFS#,}
-
-          if [ -z "${IMAGE_REFS}" ]; then
-            echo 'Error: No Docker image tags generated.' >&2
-            exit 1
-          fi
-
-          set_github_env 'IMAGE_REFS' "${IMAGE_REFS}" non-optional non-secret verbose
-
       - name: Build matrix from PUSH_PLATFORMS
         env:
           PUSH_PLATFORMS: ${{ env.PUSH_PLATFORMS }}
@@ -430,7 +376,7 @@ jobs:
         env:
           BUILD_VARIANT: ${{ env.BUILD_VARIANT }}
           PYTHON_IMAGE_TAG: ${{ env.PYTHON_IMAGE_TAG }}
-          IMAGE_REFS: ${{ env.IMAGE_REFS }}
+          IMAGE_TAGS: ${{ env.IMAGE_TAGS }}
           MATRIX_JSON: ${{ env.MATRIX_JSON }}
         run: |
           # Set job output variables
@@ -440,7 +386,7 @@ jobs:
 
           set_github_output 'build_variant' "${BUILD_VARIANT}" non-optional verbose
           set_github_output 'python_image_tag' "${PYTHON_IMAGE_TAG}" non-optional verbose
-          set_github_output 'image_refs' "${IMAGE_REFS}" non-optional verbose
+          set_github_output 'image_tags' "${IMAGE_TAGS}" non-optional verbose
           set_github_output 'matrix' "${MATRIX_JSON}" non-optional verbose
 
   # Build & push job
@@ -467,7 +413,7 @@ jobs:
 
     # Set environment variables for the job
     env:
-      IMAGE_REFS: ${{ needs.prepare.outputs.image_refs }}
+      IMAGE_TAGS: ${{ needs.prepare.outputs.image_tags }}
       BUILD_PLATFORM: ${{ matrix.platform }}
       BUILD_VARIANT: ${{ needs.prepare.outputs.build_variant }}
       PYTHON_VERSION: ${{ inputs.python_version }}
@@ -496,27 +442,6 @@ jobs:
           PLATFORM_SUFFIX="$(echo "${BUILD_PLATFORM}" | cut -d/ -f2)"
 
           set_github_env 'PLATFORM_SUFFIX' "${PLATFORM_SUFFIX}" non-optional non-secret verbose
-
-      - name: Set PLATFORM_IMAGE_REFS
-        env:
-          IMAGE_REFS: ${{ env.IMAGE_REFS }}
-          PLATFORM_SUFFIX: ${{ env.PLATFORM_SUFFIX }}
-        run: |
-          # Set PLATFORM_IMAGE_REFS environment variable
-
-          # Load helper scripts
-          . ./.github/workflows/scripts/set_github_env.sh
-
-          # Break down IMAGE_REFS into a list of image refs
-          # Append the platform suffix to each image ref
-          PLATFORM_IMAGE_REFS="$(
-            printf '%s\n' "$IMAGE_REFS" \
-            | tr ',' '\n' \
-            | sed 's/$/-'"${PLATFORM_SUFFIX}"'/' \
-            | paste -sd, -
-          )"
-
-          set_github_env 'PLATFORM_IMAGE_REFS' "${PLATFORM_IMAGE_REFS}" non-optional non-secret verbose
 
       - name: Set Docker Hub registry credentials
         if: env.DHCR_ENABLED == 'true'
@@ -589,6 +514,81 @@ jobs:
             'CUSTOM_CR_IMAGES_NAME' \
             'CUSTOM_CR_USERNAME' \
             'CUSTOM_CR_TOKEN'
+
+      - name: Set IMAGE_REFS
+        env:
+          DHCR_ENABLED: ${{ env.DHCR_ENABLED }}
+          DHCR_IMAGES_NAME: ${{ env.DHCR_IMAGES_NAME }}
+          GHCR_ENABLED: ${{ env.GHCR_ENABLED }}
+          GHCR_IMAGES_NAME: ${{ env.GHCR_IMAGES_NAME }}
+          CUSTOM_CR_ENABLED: ${{ env.CUSTOM_CR_ENABLED }}
+          CUSTOM_CR_IMAGES_NAME: ${{ env.CUSTOM_CR_IMAGES_NAME }}
+          IMAGE_TAGS: ${{ env.IMAGE_TAGS }}
+        run: |
+          # Set IMAGE_REFS environment variable
+
+          # Load helper scripts
+          . ./.github/workflows/scripts/set_github_env.sh
+
+          # Break down IMAGE_TAGS into a list of image tags
+          IMAGE_TAGS_LIST="$(
+            printf '%s\n' "$IMAGE_TAGS" \
+            | tr ',' '\n'
+          )"
+
+          IMAGE_REFS=''
+
+          # Include image refs for all tags in Docker Hub registry
+          if [ "${DHCR_ENABLED}" = "true" ] && [ -n "${DHCR_IMAGES_NAME}" ]; then
+            while IFS= read -r image_tag; do
+              IMAGE_REFS="${IMAGE_REFS},${DHCR_IMAGES_NAME}:${image_tag}"
+            done <<< "$IMAGE_TAGS_LIST"
+          fi
+
+          # Include image refs for all tags in GitHub registry
+          if [ "${GHCR_ENABLED}" = "true" ] && [ -n "${GHCR_IMAGES_NAME}" ]; then
+            while IFS= read -r image_tag; do
+              IMAGE_REFS="${IMAGE_REFS},${GHCR_IMAGES_NAME}:${image_tag}"
+            done <<< "$IMAGE_TAGS_LIST"
+          fi
+
+          # Include image refs for all tags in custom registry
+          if [ "${CUSTOM_CR_ENABLED}" = "true" ] && [ -n "${CUSTOM_CR_IMAGES_NAME}" ]; then
+            while IFS= read -r image_tag; do
+              IMAGE_REFS="${IMAGE_REFS},${CUSTOM_CR_IMAGES_NAME}:${image_tag}"
+            done <<< "$IMAGE_TAGS_LIST"
+          fi
+
+          # Remove leading comma
+          IMAGE_REFS=${IMAGE_REFS#,}
+
+          if [ -z "${IMAGE_REFS}" ]; then
+            echo 'Error: No Docker image tags generated.' >&2
+            exit 1
+          fi
+
+          set_github_env 'IMAGE_REFS' "${IMAGE_REFS}" non-optional non-secret verbose
+
+      - name: Set PLATFORM_IMAGE_REFS
+        env:
+          IMAGE_REFS: ${{ env.IMAGE_REFS }}
+          PLATFORM_SUFFIX: ${{ env.PLATFORM_SUFFIX }}
+        run: |
+          # Set PLATFORM_IMAGE_REFS environment variable
+
+          # Load helper scripts
+          . ./.github/workflows/scripts/set_github_env.sh
+
+          # Break down IMAGE_REFS into a list of image refs
+          # Append the platform suffix to each image ref
+          PLATFORM_IMAGE_REFS="$(
+            printf '%s\n' "$IMAGE_REFS" \
+            | tr ',' '\n' \
+            | sed 's/$/-'"${PLATFORM_SUFFIX}"'/' \
+            | paste -sd, -
+          )"
+
+          set_github_env 'PLATFORM_IMAGE_REFS' "${PLATFORM_IMAGE_REFS}" non-optional non-secret verbose
 
       # Execution steps
 
@@ -668,7 +668,7 @@ jobs:
     # Set environment variables for the job
     env:
       PUSH_PLATFORMS: ${{ vars.PUSH_PLATFORMS }}
-      IMAGE_REFS: ${{ needs.prepare.outputs.image_refs }}
+      IMAGE_TAGS: ${{ needs.prepare.outputs.image_tags }}
 
     steps:
 
@@ -759,6 +759,60 @@ jobs:
             'CUSTOM_CR_USERNAME' \
             'CUSTOM_CR_TOKEN'
 
+      - name: Set IMAGE_REFS
+        env:
+          DHCR_ENABLED: ${{ env.DHCR_ENABLED }}
+          DHCR_IMAGES_NAME: ${{ env.DHCR_IMAGES_NAME }}
+          GHCR_ENABLED: ${{ env.GHCR_ENABLED }}
+          GHCR_IMAGES_NAME: ${{ env.GHCR_IMAGES_NAME }}
+          CUSTOM_CR_ENABLED: ${{ env.CUSTOM_CR_ENABLED }}
+          CUSTOM_CR_IMAGES_NAME: ${{ env.CUSTOM_CR_IMAGES_NAME }}
+          IMAGE_TAGS: ${{ env.IMAGE_TAGS }}
+        run: |
+          # Set IMAGE_REFS environment variable
+
+          # Load helper scripts
+          . ./.github/workflows/scripts/set_github_env.sh
+
+          # Break down IMAGE_TAGS into a list of image tags
+          IMAGE_TAGS_LIST="$(
+            printf '%s\n' "$IMAGE_TAGS" \
+            | tr ',' '\n'
+          )"
+
+          IMAGE_REFS=''
+
+          # Include image refs for all tags in Docker Hub registry
+          if [ "${DHCR_ENABLED}" = "true" ] && [ -n "${DHCR_IMAGES_NAME}" ]; then
+            while IFS= read -r image_tag; do
+              IMAGE_REFS="${IMAGE_REFS},${DHCR_IMAGES_NAME}:${image_tag}"
+            done <<< "$IMAGE_TAGS_LIST"
+          fi
+
+          # Include image refs for all tags in GitHub registry
+          if [ "${GHCR_ENABLED}" = "true" ] && [ -n "${GHCR_IMAGES_NAME}" ]; then
+            while IFS= read -r image_tag; do
+              IMAGE_REFS="${IMAGE_REFS},${GHCR_IMAGES_NAME}:${image_tag}"
+            done <<< "$IMAGE_TAGS_LIST"
+          fi
+
+          # Include image refs for all tags in custom registry
+          if [ "${CUSTOM_CR_ENABLED}" = "true" ] && [ -n "${CUSTOM_CR_IMAGES_NAME}" ]; then
+            while IFS= read -r image_tag; do
+              IMAGE_REFS="${IMAGE_REFS},${CUSTOM_CR_IMAGES_NAME}:${image_tag}"
+            done <<< "$IMAGE_TAGS_LIST"
+          fi
+
+          # Remove leading comma
+          IMAGE_REFS=${IMAGE_REFS#,}
+
+          if [ -z "${IMAGE_REFS}" ]; then
+            echo 'Error: No Docker image tags generated.' >&2
+            exit 1
+          fi
+
+          set_github_env 'IMAGE_REFS' "${IMAGE_REFS}" non-optional non-secret verbose
+
       # Execution steps
 
       - name: Login to Docker Hub registry
@@ -839,3 +893,15 @@ jobs:
               ${TARGETS}
 
           done <<< "${IMAGE_REFS_LIST}"
+
+      - name: Set job outputs
+        id: outputs
+        env:
+          IMAGE_REFS: ${{ env.IMAGE_REFS }}
+        run: |
+          # Set job output variables
+
+          # Load helper scripts
+          . ./.github/workflows/scripts/set_github_output.sh
+
+          set_github_output 'image_refs' "${IMAGE_REFS}" non-optional verbose
